[tool.poetry]
name = "fundraising"
version = "1.1.2"
description = "An event fundraising website where individuals can create personal pages, set goals and raise money for the overall goal."
authors = ["Dominik Szopa <techdomi@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
requests = "2.28.2"
certifi = "2022.12.7"
chardet = "3.0.4"
django = "2.2.28"
django-crispy-forms = "1.7.2"
django-debug-toolbar = "2.2.1"
django-paypal = "1.0.0"
idna = "2.8"
pillow = "9.3.0"
python-dotenv = "0.10.3"
pytz = "2019.2"
six = "1.12.0"
sqlparse = "0.3.0"
urllib3 = "1.26.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
